### ISSUE TITLE
SlackBot

### ISSUE THREAD

**Issue by paulchubatyy** [vterdunov/janna#2]
Было бы круто сделать также slackbot, которым можно бы было пообщатся и задеплоить машину в vCenter.

**Comment by vterdunov** [comment]
@paulchubatyy 
Не будет ли это работать через существующие решения в виде слаботов? Того же хубота.
Дёрнуть API Жанны не представляется мне проблемой. Только изящность решения. Запрос от одного бота - ответ от другого.

**Comment by paulchubatyy** [comment]
Так тоже норм.

**Comment by vterdunov** [comment]
Ок, закрываю. Пока выглядит как ненужное.
